set(Uncertainty_PRECOMPILE_INCLUDES
<iAConnector.h>
<iAEnsemble.h>
<iAEnsembleDescriptorFile.h>
<iAImageData.h>
<iALog.h>
<iASingleResult.h>
<iASlicerMode.h>
<iAUncertaintyColors.h>
<iAUncertaintyImages.h>
<QHBoxLayout>
<QVector>
<QWidget>
<vtkColorTransferFunction.h>
<vtkImageData.h>
<vtkLookupTable.h>
<vtkSmartPointer.h>)
