set(OPENIA_PRECOMPILE_HEADERS
<array>
<iALinePointers.h>
<iALog.h>
<iAMathUtility.h>
<iAProfileColors.h>
<iARulerActor.h>
<iARulerRepresentation.h>
<iARulerWidget.h>
<iASlicerInteractorStyle.h>
<iASlicerProfile.h>
<iASlicerProfileHandles.h>
<iAvtkSourcePoly.h>
<iAVtkText.h>
<vtkActor.h>
<vtkActor2D.h>
<vtkCamera.h>
<vtkCellArray.h>
<vtkCellData.h>
<vtkConeSource.h>
<vtkCoordinate.h>
<vtkCubeSource.h>
<vtkDiskSource.h>
<vtkImageData.h>
<vtkInteractorStyleImage.h>
<vtkLineSource.h>
<vtkMath.h>
<vtkObjectFactory.h>
<vtkPoints.h>
<vtkPolyData.h>
<vtkPolyDataMapper.h>
<vtkProperty.h>
<vtkRenderer.h>
<vtkRendererCollection.h>
<vtkRenderWindow.h>
<vtkRenderWindowInteractor.h>
<vtkSmartPointer.h>
<vtkTextProperty.h>
)
