set(OPENIA_PRECOMPILE_HEADERS
<algorithm>
<array>
<cassert>
<cmath>
<cstddef>
<limits>
<memory>
<vector>
<iAAbortListener.h>
<iAAttributeDescriptor.h>
<iAAttributes.h>
<iAConnector.h>
<iADataSet.h>
<iAExtendedTypedCallHelper.h>
<iAFileUtils.h>
<iAFilter.h>
<iAFilterRegistry.h>
<iAITKIO.h>
<iALog.h>
<iAMathUtility.h>
<iAProgress.h>
<iAStringHelper.h>
<iAToolsITK.h>
<iAToolsVTK.h>
<iATransferFunction.h>
<iATypedCallHelper.h>
<iAValueType.h>
<iAVec3.h>
<iostream>
<itkImageBase.h>
<itkImageFileReader.h>
<itkImageFileWriter.h>
<QColor>
<QFileInfo>
<QFlags>
<QMap>
<QObject>
<QRegularExpression>
<QSharedPointer>
<QString>
<QStringList>
<QTextStream>
<QVariant>
<QVector>
<vtkColorTransferFunction.h>
<vtkCommand.h>
<vtkImageData.h>
<vtkLookupTable.h>
<vtkPiecewiseFunction.h>
<vtkPolyData.h>
<vtkSmartPointer.h>
)
