SET (OPENIA_PRECOMPILE_HEADERS
<algorithm>
<cassert>
<cmath>
<cstddef>
<iAAbortListener.h>
<iAAttributeDescriptor.h>
<iAAttributes.h>
<iAConnector.h>
<iAFileUtils.h>
<iAFilter.h>
<iAITKIO.h>
<iAItkVersion.h>
<iALog.h>
<iAMathUtility.h>
<iAStringHelper.h>
<iAToolsITK.h>
<iATransferFunction.h>
<iATypedCallHelper.h>
<iAValueType.h>
<itkImageBase.h>
<itkImageFileReader.h>
<itkImageFileWriter.h>
<itkImageIOBase.h>
<QColor>
<QFileInfo>
<QMap>
<QObject>
<QRegularExpression>
<QSharedPointer>
<QString>
<QStringList>
<QTextStream>
<QtGlobal>
<QVector>
<vector>
<vtkColorTransferFunction.h>
<vtkImageData.h>
<vtkPiecewiseFunction.h>
<vtkSmartPointer.h>
)
