SET (FeatureAnalyzerComputation_PRECOMPILE_INCLUDES
<defines.h>
<dlg_ParamSpaceSampling.h>
<FeatureAnalyzerHelpers.h>
<iACSVToQTableWidgetConverter.h>
<iADatasetInfo.h>
<iADragFilterWidget.h>
<iADropPipelineWidget.h>
<iAFeatureAnalyzerComputationModuleInterface.h>
<iAFileUtils.h>
<iAITKIO.h>
<iARunBatchThread.h>
<itkExtractImageFilter.h>
<itkImage.h>
<itkImageDuplicator.h>
<itkImageFileWriter.h>
<itkImageToHistogramFilter.h>
<itkMedianImageFilter.h>
<itkRescaleIntensityImageFilter.h>
<QDebug>
<QDir>
<QFile>
<QLabel>
<QList>
<QMessageBox>
<QPixmap>
<QScrollArea>
<QSettings>
<QString>
<QStringList>
<QTableWidget>
<QTextEdit>
<QThread>
<QTime>
)
