set(FeatureAnalyzerComputation_PRECOMPILE_INCLUDES
<defines.h>
<FeatureAnalyzerHelpers.h>
<iAFeatureAnalyzerComputationModuleInterface.h>
<iAITKIO.h>
<QDebug>
<QDir>
<QLabel>
<QList>
<QMessageBox>
<QString>
<QStringList>
<QTableWidget>)
