SET( DEPENDENCIES_CMAKE
	OPENCL_FOUND
)

# Toolkit directories
SET( DEPENDENCIES_IA_TOOLKIT_DIRS
	OpenCL
)

SET( DEPENDENCIES_LIBRARIES
	${OPENCL_LIBRARIES}
)

# if OPENCL includes not set via ITK:
IF ("${ITKGPUCommon_LIBRARY_DIRS}" STREQUAL "")
SET( DEPENDENCIES_INCLUDE_DIRS
	${OPENCL_INCLUDE_DIRS}
)
ENDIF()