SET( DEPENDENCIES_LIBRARIES
	${OPENCL_LIBRARIES}
	iAcharts
	iAcore
)
SET( DEPENDENCIES_CMAKE
	OPENCL_FOUND
)
SET( DEPENDENCIES_COMPILE_DEFINITIONS
	CL_HPP_TARGET_OPENCL_VERSION=${CL_HPP_TARGET_OPENCL_VERSION}
	CL_TARGET_OPENCL_VERSION=${CL_TARGET_OPENCL_VERSION}
)
SET( DEPENDENCIES_IA_TOOLKIT_DIRS
	OpenCL
)
# if OPENCL includes not set via ITK:
IF ("${ITKGPUCommon_LIBRARY_DIRS}" STREQUAL "")
	SET( DEPENDENCIES_INCLUDE_DIRS
		${OPENCL_INCLUDE_DIRS}
	)
ENDIF()
