set(FuzzyFeatureTracking_PRECOMPILE_INCLUDES
<dlg_trackingGraph.h>
<iAFeatureTracking.h>
<iAGraph.h>
<iALog.h>
<iAQVTKWidget.h>
<iAVolumeStack.h>
<vector>
<vtkContextScene.h>
<vtkDataSetAttributes.h>
<vtkMutableDirectedGraph.h>
<vtkSmartPointer.h>)
