if (NOT Qt${QT_VERSION_MAJOR}Charts_DIR)
	set (Qt${QT_VERSION_MAJOR}Charts_DIR "${Qt${QT_VERSION_MAJOR}_DIR}Charts" CACHE PATH "" FORCE)
endif()
find_package(Qt${QT_VERSION_MAJOR}Charts REQUIRED)

SET( DEPENDENCIES_LIBRARIES
	Qt${QT_VERSION_MAJOR}::Charts
	iAcharts
	iAguibase
)
SET( DEPENDENCIES_MODULES
	Segmentation
)
