SET (OPENIA_PRECOMPILE_HEADERS
<algorithm>
<cassert>
<cmath>
<cstddef>
<iAChartFunction.h>
<iAChartFunctionBezier.h>
<iAChartFunctionGaussian.h>
<iAChartFunctionTransfer.h>
<iAChartWidget.h>
<iAChartWithFunctionsWidget.h>
<iAFunctionColors.h>
<iAHistogramData.h>
<iALog.h>
<iALookupTable.h>
<iALUT.h>
<iAMapper.h>
<iAMathUtility.h>
<iAPlot.h>
<iAPlotData.h>
<iAPlotTypes.h>
<iAScatterPlot.h>
<iAScatterPlotViewData.h>
<iASPLOMData.h>
<iAStringHelper.h>
<iATFTableDlg.h>
<QAbstractTextDocumentLayout>
<QColor>
<QColorDialog>
<QFileDialog>
<QList>
<QMenu>
<QMessageBox>
<QMouseEvent>
<QObject>
<QOpenGLWidget>
<QPainter>
<QPen>
<QPolygon>
<QPropertyAnimation>
<QSharedPointer>
<QString>
<QtGlobal>
<QtMath>
<QToolTip>
<QVector>
<QWheelEvent>
<QWidget>
<vector>
<vtkColorTransferFunction.h>
<vtkImageData.h>
<vtkLookupTable.h>
<vtkMath.h>
<vtkPiecewiseFunction.h>
<vtkSmartPointer.h>
)
