set(OPENIA_PRECOMPILE_HEADERS
<algorithm>
<cassert>
<cstddef>
<iAChartFunction.h>
<iAChartFunctionBezier.h>
<iAChartFunctionGaussian.h>
<iAChartFunctionTransfer.h>
<iAChartWidget.h>
<iAChartWithFunctionsWidget.h>
<iAColorTheme.h>
<iAHistogramData.h>
<iALog.h>
<iALookupTable.h>
<iALUT.h>
<iAMapper.h>
<iAMathUtility.h>
<iAPlot.h>
<iAPlotData.h>
<iAPlotTypes.h>
<iAQGLWidget.h>
<iAScatterPlot.h>
<iAScatterPlotViewData.h>
<iASPLOMData.h>
<iAStringHelper.h>
<iATFTableDlg.h>
<iAThemeHelper.h>
<iAToolsVTK.h>
<QAbstractTextDocumentLayout>
<QAction>
<QActionGroup>
<QApplication>
<QColor>
<QColorDialog>
<QFileDialog>
<QIcon>
<QList>
<QMap>
<QMenu>
<QMessageBox>
<QMouseEvent>
<QObject>
<QOpenGLDebugLogger>
<QOpenGLFunctions>
<QOpenGLWidget>
<QPainter>
<QPen>
<QPolygon>
<QSharedPointer>
<QString>
<QVector>
<QWheelEvent>
<QWidget>
<utility>
<vector>
<vtkColorTransferFunction.h>
<vtkLookupTable.h>
<vtkMath.h>
<vtkPiecewiseFunction.h>
)
