set(Segmentation_PRECOMPILE_INCLUDES
<cmath>
<defines.h>
<iAFilterDefault.h>
<iAImageCoordinate.h>
<iAImageData.h>
<iAImageGraph.h>
<iALog.h>
<iAProgress.h>
<iASeedType.h>
<iAToolsITK.h>
<iATypedCallHelper.h>
<iAVectorArray.h>
<iAVectorDistanceImpl.h>
<iAVectorType.h>
<iAVectorTypeImpl.h>
<memory>
<QString>
<QVector>
<utility>
<vtkImageData.h>)
