TARGET_LINK_LIBRARIES(${libname} PRIVATE iAcharts iAqthelper iArenderer iAslicer)
TARGET_LINK_LIBRARIES(${libname} PUBLIC iAcore)
if (openiA_CHART_OPENGL)
	TARGET_COMPILE_DEFINITIONS(${libname} PRIVATE CHART_OPENGL)
endif()
