set(OPENIA_PRECOMPILE_HEADERS
<cassert>
<dlg_datatypeconversion.h>
<dlg_slicer.h>
<dlg_volumePlayer.h>
<iAChannelData.h>
<iAChannelSlicerData.h>
<iAChartWidget.h>
<iADataSet.h>
<iADataSetRenderer.h>
<iADockWidgetWrapper.h>
<iAFileParamDlg.h>
<iAFileStackParams.h>
<iAFileTypeRegistry.h>
<iAFileUtils.h>
<iAImageStackFileIO.h>
<iAJobListView.h>
<iALog.h>
<iALogLevelMappings.h>
<iALogWidget.h>
<iAMathUtility.h>
<iAParameterDlg.h>
<iAPreferences.h>
<iAProgress.h>
<iARawFileIO.h>
<iARawFileParamDlg.h>
<iARawFileParameters.h>
<iARenderSettings.h>
<iASavableProject.h>
<iASettings.h>
<iASlicerImpl.h>
<iASlicerMode.h>
<iASlicerSettings.h>
<iAStringHelper.h>
<iASystemThemeWatcher.h>
<iAThemeHelper.h>
<iATLGICTLoader.h>
<iATool.h>
<iAToolRegistry.h>
<iAToolsVTK.h>
<iATransferFunction.h>
<iAVolumeSettings.h>
<iAVolumeStack.h>
<iAvtkInteractStyleActor.h>
<memory>
<QApplication>
<QCheckBox>
<QCloseEvent>
<QComboBox>
<QFileDialog>
<QFileInfo>
<QMap>
<QMdiSubWindow>
<QMessageBox>
<QObject>
<QSettings>
<QSharedPointer>
<QString>
<QtConcurrent>
<QTimer>
<QVariant>
<vector>
<vtkCamera.h>
<vtkColorTransferFunction.h>
<vtkImageData.h>
<vtkImageReslice.h>
<vtkMath.h>
<vtkOpenGLRenderer.h>
<vtkPiecewiseFunction.h>
<vtkPolyData.h>
<vtkProperty.h>
<vtkRenderer.h>
<vtkRenderWindow.h>
<vtkSmartPointer.h>
<vtkTransform.h>
)
