set(OPENIA_PRECOMPILE_HEADERS
<array>
<iAAboutDlg.h>
<iAAttributes.h>
<iAChannelSlicerData.h>
<iADataSetRenderer.h>
<iADockWidgetWrapper.h>
<iAFileParamDlg.h>
<iAFileStackParams.h>
<iAFileTypeRegistry.h>
<iAFileUtils.h>
<iAImageData.h>
<iAImageStackFileIO.h>
<iAJobListView.h>
<iALog.h>
<iALogLevelMappings.h>
<iALogWidget.h>
<iAMathUtility.h>
<iAMdiChild.h>
<iAParameterDlg.h>
<iAPreferences.h>
<iAProgress.h>
<iARawFileIO.h>
<iARawFileParamDlg.h>
<iARawFileParameters.h>
<iARawFilePreviewSlicer.h>
<iARunAsync.h>
<iASavableProject.h>
<iASettings.h>
<iASlicerContainer.h>
<iASlicerImpl.h>
<iASlicerMode.h>
<iASlicerSettings.h>
<iAStringHelper.h>
<iASystemThemeWatcher.h>
<iAThemeHelper.h>
<iATLGICTLoader.h>
<iAToolsVTK.h>
<iAValueTypeVectorHelpers.h>
<iAvtkInteractStyleActor.h>
<memory>
<QApplication>
<QCloseEvent>
<QComboBox>
<QFileDialog>
<QFileInfo>
<QLabel>
<QMap>
<QMessageBox>
<QObject>
<QPushButton>
<QRegularExpression>
<QSettings>
<QSpinBox>
<QString>
<QtConcurrent>
<QWindow>
<vtkCamera.h>
<vtkColorTransferFunction.h>
<vtkImageData.h>
<vtkImageReslice.h>
<vtkRenderer.h>
<vtkSmartPointer.h>
<vtkTransform.h>
)
