set(MetaFilters_PRECOMPILE_INCLUDES
<iAAttributeDescriptor.h>
<iAAttributes.h>
<iADataSet.h>
<iAFileTypeRegistry.h>
<iAFileUtils.h>
<iAFilterDefault.h>
<iAFilter.h>
<iAFilterRegistry.h>
<iAITKIO.h>
<iALog.h>
<iANameMapper.h>
<iAParameterNames.h>
<iAProgress.h>
<iASampleOperation.h>
<iASamplingMethod.h>
<iASamplingMethodImpl.h>
<iASamplingResults.h>
<iASingleResult.h>
<iAStringHelper.h>
<iAToolsITK.h>
<QDir>
<QFile>
<QFileInfo>
<QMap>
<QSharedPointer>
<QString>
<QTextStream>
<QThread>
<QVector>)
