set(Remote_PRECOMPILE_INCLUDES
<iADockWidgetWrapper.h>
<iALog.h>
<iAMdiChild.h>
<iAPlaneSliceTool.h>
<iARemotePortSettings.h>
<iARenderer.h>
<iAStringHelper.h>
<iATool.h>
<iAWebsocketAPI.h>
<memory>
<QElapsedTimer>
<QHeaderView>
<QObject>
<QTableWidget>
<QWebSocketServer>
<vtkRendererCollection.h>
<vtkRenderWindow.h>)
