if (RenderingOpenVR IN_LIST VTK_COMPONENTS)
	set(BUILD_INFO "${BUILD_INFO}    \"OpenVR	${OpenVR_VERSION_MAJOR}.${OpenVR_VERSION_MINOR}.${OpenVR_VERSION_PATCH}\\n\"\n")
endif()

if (RenderingOpenXR IN_LIST VTK_COMPONENTS)
	set(BUILD_INFO "${BUILD_INFO}    \"OpenXR	${OpenXR_VERSION}\\n\"\n")
endif()

set(VTK_VERSION_MAJMIN "${VTK_VERSION_MAJOR}.${VTK_VERSION_MINOR}")
set(VR_INSTALL_SRC_SUBDIRS images "action_manifests/vtk${VTK_VERSION_MAJMIN}")
set(VR_INSTALL_DST_SUBDIRS VR-skybox VR-input-manifests)
list(LENGTH VR_INSTALL_SRC_SUBDIRS VR_INSTALL_DIRS_COUNT)
math(EXPR VR_INSTALL_DIRS_COUNT "${VR_INSTALL_DIRS_COUNT} - 1") # subtract one since foreach loop includes end index

foreach (VR_INSTALL_DIR_IDX RANGE ${VR_INSTALL_DIRS_COUNT})
	list(GET VR_INSTALL_SRC_SUBDIRS ${VR_INSTALL_DIR_IDX} VR_SRC_SUBDIR)
	list(GET VR_INSTALL_DST_SUBDIRS ${VR_INSTALL_DIR_IDX} VR_DST_SUBDIR)
	set(VR_INSTALL_SRC_DIR "${CMAKE_CURRENT_SOURCE_DIR}/ImNDT/${VR_SRC_SUBDIR}/")

	add_custom_command(TARGET ImNDT POST_BUILD
		COMMAND ${CMAKE_COMMAND} "-DSOURCE_DIR=${VR_INSTALL_SRC_DIR}" "-DTARGET_DIR=$<TARGET_FILE_DIR:iA::guibase>/${VR_DST_SUBDIR}" -P "${CMAKE_CURRENT_SOURCE_DIR}/../cmake/copy-if-newer.cmake")
	install(DIRECTORY "${VR_INSTALL_SRC_DIR}" DESTINATION ${VR_DST_SUBDIR})
endforeach()
