set(FeatureScout_PRECOMPILE_INCLUDES
<dlg_FeatureScout.h>
<iABlobCluster.h>
<iABlobManager.h>
<iAFileUtils.h>
<iALog.h>
<iAMainWindow.h>
<iAMdiChild.h>
<iAObjectType.h>
<iAToolsVTK.h>
<QList>
<QMessageBox>
<QObject>
<QSettings>
<QSharedPointer>
<vector>
<vtkActor.h>
<vtkImageData.h>
<vtkPolyDataMapper.h>
<vtkProperty.h>
<vtkRenderer.h>
<vtkRenderWindow.h>
<vtkSmartPointer.h>
<vtkTable.h>
<vtkTextProperty.h>)
