SET (FeatureScout_PRECOMPILE_INCLUDES <iA3DColoredPolyObjectVis.h>
<iA3DLineObjectVis.h>
<iA3DObjectVis.h>
<iABlobCluster.h>
<iABlobManager.h>
<iAConsole.h>
<iACsvConfig.h>
<iACsvIO.h>
<iAFeatureScoutObjectType.h>
<iALookupTable.h>
<iARenderer.h>
<iAvec3.h>
<map>
<mdichild.h>
<QColor>
<QDialogButtonBox>
<QFileDialog>
<QList>
<QMap>
<QMessageBox>
<QSettings>
<QString>
<QTextStream>
<qthelper/iAQTtoUIConnector.h>
<QVector>
<vector>
<vtkActor.h>
<vtkColorTransferFunction.h>
<vtkFloatArray.h>
<vtkImageData.h>
<vtkMath.h>
<vtkObjectFactory.h>
<vtkOpenGLRenderer.h>
<vtkOutlineFilter.h>
<vtkPointData.h>
<vtkPolyData.h>
<vtkPolyDataMapper.h>
<vtkProperty.h>
<vtkRenderer.h>
<vtkRendererCollection.h>
<vtkSmartPointer.h>
<vtkTable.h>
<vtkVersion.h>)
