FIND_PACKAGE(OpenVR)
# HINTS ${OPENVR_PATH} # leads to OpenVR not being found at all...?

IF (OPENVR_FOUND AND vtkRenderingOpenVR_LOADED)
	MESSAGE(STATUS "OpenVR SDK: ${OPENVR_VERSION_MAJOR}.${OPENVR_VERSION_MINOR}.${OPENVR_VERSION_BUILD} in ${OPENVR_ROOT_DIR}.")
ELSE()
	MESSAGE(STATUS "OpenVR SDK: Not found.")
ENDIF()

SET (DEPENDENCIES_MODULES_NEW
	FeatureScout
)

SET( DEPENDENCIES_CMAKE
	vtkRenderingOpenVR_LOADED
)

SET( DEPENDENCIES_LIBRARIES
	${OPENVR_LIBRARY}
)

SET( DEPENDENCIES_INCLUDE_DIRS
	${OPENVR_INCLUDE_DIR}
)

SET( DEPENDENCIES_COMPILE_DEFINITIONS
	OPENVR_VERSION_MAJOR=${OPENVR_VERSION_MAJOR} OPENVR_VERSION_MINOR=${OPENVR_VERSION_MINOR} OPENVR_VERSION_BUILD=${OPENVR_VERSION_BUILD}
)