set(BUILD_INFO "${BUILD_INFO}    \"OpenVR SDK: ${OPENVR_VERSION_MAJOR}.${OPENVR_VERSION_MINOR}.${OPENVR_VERSION_BUILD}\\n\"\n" PARENT_SCOPE)

set(SKYBOX_SRC_DIR "${CMAKE_CURRENT_SOURCE_DIR}/VR/images/")
foreach (cfg ${CMAKE_CONFIGURATION_TYPES})
	string(TOUPPER "${cfg}" CFG)
	set(SKYBOX_BIN_DIR "${CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CFG}}/VR-skybox")
	if (NOT EXISTS "${SKYBOX_BIN_DIR}")
		file(COPY "${SKYBOX_SRC_DIR}" DESTINATION "${SKYBOX_BIN_DIR}")
	endif()
endforeach()

install(DIRECTORY "${SKYBOX_SRC_DIR}" DESTINATION VR-skybox)