SET (OPENIA_PRECOMPILE_HEADERS
<itkImage.h>
<itkImageBase.h>
<itkImageFileReader.h>
<itkImageIOBase.h>

<QColor>
<QComboBox>
<QDateTime>
<QDir>
<QDockWidget>
<QFile>
<QFileDialog>
<QFileInfo>
<QImage>
<QLineEdit>
<QList>
<QMap>
<QMenu>
<QMessageBox>
<QMouseEvent>
<QObject>
<QPainter>
<QPen>
<QSettings>
<QSharedPointer>
<QString>
<QStringList>
<QTableWidget>
<QTextStream>
<QtGlobal>
<QThread>
<QtMath>
<QVariant>
<QVector>
<QVTKInteractor.h>
<QWidget>

<vtkActor.h>
<vtkActor2D.h>
<vtkCamera.h>
<vtkCellArray.h>
<vtkColorTransferFunction.h>
<vtkCommand.h>
<vtkDiskSource.h>
<vtkGenericOpenGLRenderWindow.h>
<vtkImageActor.h>
<vtkImageCast.h>
<vtkImageData.h>
<vtkImageMapper3D.h>
<vtkImageMapToColors.h>
<vtkImageReslice.h>
<vtkLineSource.h>
<vtkLookupTable.h>
<vtkMath.h>
<vtkObjectFactory.h>
<vtkOpenGLRenderer.h>
<vtkPiecewiseFunction.h>
<vtkPointData.h>
<vtkPoints.h>
<vtkPolyData.h>
<vtkPolyDataMapper.h>
<vtkPolyDataMapper2D.h>
<vtkPolyLine.h>
<vtkProperty.h>
<vtkRenderer.h>
<vtkRendererCollection.h>
<vtkRenderWindow.h>
<vtkRenderWindowInteractor.h>
<vtkSmartPointer.h>
<vtkTextProperty.h>
<vtkTransform.h>
<vtkVersion.h>
<vtkVolume.h>
<vtkWindowToImageFilter.h>

<algorithm>
<cassert>
<cmath>
<cstddef>
<iostream>
<limits>
<string>
<vector>)