set(OPENIA_PRECOMPILE_HEADERS
<iAColMap.h>
<iAColoredPolyObjectVis.h>
<iACsvConfig.h>
<iACsvIO.h>
<iACsvQTableCreator.h>
<iACsvVectorTableCreator.h>
<iACsvVtkTableCreator.h>
<iACylinderObjectVis.h>
<iADefaultSettings.h>
<iAEllipsoidObjectVis.h>
<iALineObjectVis.h>
<iALog.h>
<iANoObjectVis.h>
<iAObjectsData.h>
<iAObjectsViewer.h>
<iAObjectType.h>
<iAObjectVis.h>
<iAObjectVisActor.h>
<iAObjectVisFactory.h>
<iAPolyObjectVisActor.h>
<iAVec3.h>
<iAvtkTubeFilter.h>
<memory>
<QColor>
<QFile>
<QFileInfo>
<QMap>
<QSettings>
<QString>
<QStringList>
<QTextStream>
<vector>
<vtkActor.h>
<vtkCellArray.h>
<vtkColorTransferFunction.h>
<vtkDoubleArray.h>
<vtkEllipsoidSource.h>
<vtkFloatArray.h>
<vtkInformation.h>
<vtkInformationVector.h>
<vtkMath.h>
<vtkObjectFactory.h>
<vtkPointData.h>
<vtkPolyData.h>
<vtkPolyDataAlgorithm.h>
<vtkPolyLine.h>
<vtkRenderer.h>
<vtkSmartPointer.h>
<vtkTable.h>
)
