SET (OPENIA_PRECOMPILE_HEADERS
<iA3DColoredPolyObjectVis.h>
<iA3DLineObjectVis.h>
<iA3DObjectVis.h>
<iACsvConfig.h>
<iACsvIO.h>
<iACsvQTableCreator.h>
<iACsvVectorTableCreator.h>
<iALog.h>
<iAObjectType.h>
<iAVec3.h>
<iAvtkTubeFilter.h>
<QColor>
<QFile>
<QMap>
<QSettings>
<QSharedPointer>
<QString>
<QTextStream>
<QVector>
<vector>
<vtkActor.h>
<vtkCellArray.h>
<vtkColorTransferFunction.h>
<vtkDoubleArray.h>
<vtkEllipsoidSource.h>
<vtkFloatArray.h>
<vtkGenericOpenGLRenderWindow.h>
<vtkInformation.h>
<vtkInformationVector.h>
<vtkMath.h>
<vtkObjectFactory.h>
<vtkOutlineFilter.h>
<vtkPointData.h>
<vtkPolyData.h>
<vtkPolyDataAlgorithm.h>
<vtkPolyDataMapper.h>
<vtkPolyLine.h>
<vtkRenderer.h>
<vtkRendererCollection.h>
<vtkSmartPointer.h>
<vtkTable.h>
<vtkUnsignedCharArray.h>
)
