# iAnalyseToolkit directories
SET (DEPENDENCIES_IA_TOOLKIT_DIRS
	MaximumDistance
)

SET( DEPENDENCIES_LIBRARIES
	${CMAKE_CURRENT_BINARY_DIR}/$(Configuration)/FeatureScout.lib
)

SET (DEPENDENCIES_INCLUDE_DIRS
	${CMAKE_CURRENT_SOURCE_DIR}/FeatureScout
)