# iAnalyseToolkit directories
SET (DEPENDENCIES_IA_TOOLKIT_DIRS
	MaximumDistance
)

SET (DEPENDENCIES_LIBRARIES
	${openiA_MODULE_LIB_DIR}/FeatureScout.lib
)

SET (DEPENDENCIES_INCLUDE_DIRS
	${CMAKE_CURRENT_SOURCE_DIR}/FeatureScout
)