SET (PorosityAnalyser_PRECOMPILE_INCLUDES <defines.h>
<iAConsole.h>
<iACSVToQTableWidgetConverter.h>
<iALUT.h>
<iAPorosityAnalyserModuleInterface.h>
<iARangeSliderDiagramData.h>
<iASegm3DView.h>
<iASelection.h>
<iAVtkWidget.h>
<iAVtkWidgetFwd.h>
<io/iAITKIO.h>
<itkImage.h>
<mainwindow.h>
<PorosityAnalyserHelpers.h>
<QCheckBox>
<QDebug>
<QDir>
<QDockWidget>
<QFileDialog>
<QLabel>
<QList>
<QMap>
<QMenu>
<QMessageBox>
<QModelIndex>
<QPixmap>
<QScopedPointer>
<QSettings>
<QString>
<QStringList>
<QTableWidget>
<qthelper/iAQTtoUIConnector.h>
<QThread>
<QTreeWidget>
<vtkColorTransferFunction.h>
<vtkIdTypeArray.h>
<vtkImageData.h>
<vtkLookupTable.h>
<vtkPiecewiseFunction.h>
<vtkRenderer.h>
<vtkRenderWindow.h>
<vtkScalarBarActor.h>
<vtkSelection.h>
<vtkSmartPointer.h>
<vtkTransform.h>)
