SET (XRF_PRECOMPILE_INCLUDES <algorithm>
<cassert>
<dlg_XRF.h>
<iAAccumulatedXRFData.h>
<iACharacteristicEnergy.h>
<iAElementalDecomposition.h>
<iAElementConcentrations.h>
<iAElementConstants.h>
<iAElementSelectionListener.h>
<iAEnergySpectrum.h>
<iAFunctionalBoxplot.h>
<iAMathUtility.h>
<iASpectrumFilter.h>
<iATypedCallHelper.h>
<iAXRFData.h>
<mdichild.h>
<QFileDialog>
<QImage>
<QMap>
<QMouseEvent>
<QPainter>
<QSharedPointer>
<qthelper/iAQTtoUIConnector.h>
<QVector>
<QWidget>
<vector>
<vtkColorTransferFunction.h>
<vtkImageData.h>
<vtkMath.h>
<vtkPiecewiseFunction.h>
<vtkSmartPointer.h>)
