set(OPENIA_PRECOMPILE_HEADERS
<cassert>
<chrono>
<cmath>
<memory>
<string>
<vector>
<defines.h>
<iAAbortListener.h>
<iAAttributeDescriptor.h>
<iAAttributes.h>
<iAChannelData.h>
<iAChannelSlicerData.h>
<iAConnector.h>
<iADataSet.h>
<iAFast3DMagicLensWidget.h>
<iAFileUtils.h>
<iAFilter.h>
<iAFilterRegistry.h>
<iAFilterRunnerGUI.h>
<iAFilterRunnerRegistry.h>
<iAFilterSelectionDlg.h>
<iAGUIModuleInterface.h>
<iAJobListView.h>
<iALog.h>
<iALogger.h>
<iAMainWindow.h>
<iAMathUtility.h>
<iAMdiChild.h>
<iAParameterDlg.h>
<iAPerformanceHelper.h>
<iAProgress.h>
<iAQMenuHelper.h>
<iAQVTKWidget.h>
<iARawFileParamDlg.h>
<iARawFileParameters.h>
<iASlicerMode.h>
<iAStringHelper.h>
<iATool.h>
<iAToolRegistry.h>
<iAToolsVTK.h>
<iATransferFunction.h>
<iATypedCallHelper.h>
<iAValueType.h>
<iAValueTypeVectorHelpers.h>
<iAVectorInput.h>
<iAVolumeRenderer.h>
<iAVolumeSettings.h>
<iAXmlSettings.h>
<itkImage.h>
<QApplication>
<QCheckBox>
<QColor>
<QComboBox>
<QDialog>
<QDir>
<QElapsedTimer>
<QEvent>
<QFileDialog>
<QFileInfo>
<QHBoxLayout>
<QLabel>
<QLineEdit>
<QList>
<QMainWindow>
<QMap>
<QMenu>
<QMessageBox>
<QObject>
<QPushButton>
<QRegularExpression>
<QScrollArea>
<QSettings>
<QSharedPointer>
<QSpinBox>
<QStatusBar>
<QString>
<QStringList>
<QThread>
<QToolButton>
<QVariant>
<QVector>
<QVTKInteractor.h>
<QWidget>
<vtkActor.h>
<vtkActor2D.h>
<vtkCamera.h>
<vtkCellArray.h>
<vtkColorTransferFunction.h>
<vtkGenericOpenGLRenderWindow.h>
<vtkImageActor.h>
<vtkImageData.h>
<vtkImageMapper3D.h>
<vtkImageMapToColors.h>
<vtkImageReslice.h>
<vtkLineSource.h>
<vtkMath.h>
<vtkOpenGLRenderer.h>
<vtkOutlineFilter.h>
<vtkPiecewiseFunction.h>
<vtkPointData.h>
<vtkPolyData.h>
<vtkPolyDataMapper.h>
<vtkPolyDataMapper2D.h>
<vtkPolyLine.h>
<vtkProperty.h>
<vtkProperty2D.h>
<vtkRenderer.h>
<vtkRendererCollection.h>
<vtkRenderWindow.h>
<vtkScalarsToColors.h>
<vtkSmartPointer.h>
<vtkTextProperty.h>
)
