set(OPENIA_PRECOMPILE_HEADERS
<cassert>
<chrono>
<defines.h>
<iAAABB.h>
<iAAbortListener.h>
<iAAttributeDescriptor.h>
<iAAttributes.h>
<iAChannelData.h>
<iAChannelSlicerData.h>
<iADataSet.h>
<iADataSetListWidget.h>
<iADataSetRenderer.h>
<iADataSetRendererImpl.h>
<iADataSetViewer.h>
<iAFileChooserWidget.h>
<iAFileUtils.h>
<iAFilter.h>
<iAFilterRegistry.h>
<iAFilterRunnerGUI.h>
<iAFilterRunnerRegistry.h>
<iAFilterSelectionDlg.h>
<iAGeometricObject.h>
<iAGUIModuleInterface.h>
<iAJobListView.h>
<iALog.h>
<iAMainWindow.h>
<iAMathUtility.h>
<iAMdiChild.h>
<iAParameterDlg.h>
<iAPerformanceHelper.h>
<iAPreferences.h>
<iAProgress.h>
<iAQMenuHelper.h>
<iAQVTKWidget.h>
<iARenderer.h>
<iARunAsync.h>
<iASlicerMode.h>
<iAStringHelper.h>
<iATool.h>
<iAToolRegistry.h>
<iAToolsVTK.h>
<iATransferFunction.h>
<iATransferFunctionOwner.h>
<iAValueType.h>
<iAValueTypeVectorHelpers.h>
<iAVectorInput.h>
<iAVolumeRenderer.h>
<iAVolumeViewer.h>
<memory>
<QAction>
<QApplication>
<QCheckBox>
<QColor>
<QComboBox>
<QDialog>
<QEvent>
<QFileDialog>
<QFileInfo>
<QHBoxLayout>
<QLabel>
<QLineEdit>
<QList>
<QMainWindow>
<QMap>
<QMenu>
<QObject>
<QPushButton>
<QRegularExpression>
<QScrollArea>
<QSettings>
<QSpinBox>
<QStatusBar>
<QString>
<QThread>
<QToolButton>
<QVariant>
<QVBoxLayout>
<QVector>
<QWidget>
<vtkActor.h>
<vtkActor2D.h>
<vtkCallbackCommand.h>
<vtkCamera.h>
<vtkCellArray.h>
<vtkColorTransferFunction.h>
<vtkGenericOpenGLRenderWindow.h>
<vtkImageActor.h>
<vtkImageData.h>
<vtkImageMapper3D.h>
<vtkImageMapToColors.h>
<vtkImageReslice.h>
<vtkLineSource.h>
<vtkMath.h>
<vtkOpenGLRenderer.h>
<vtkPiecewiseFunction.h>
<vtkPointData.h>
<vtkPolyData.h>
<vtkPolyDataMapper.h>
<vtkPolyDataMapper2D.h>
<vtkPolyLine.h>
<vtkProperty.h>
<vtkProperty2D.h>
<vtkRenderer.h>
<vtkScalarsToColors.h>
<vtkSmartPointer.h>
<vtkSphereSource.h>
<vtkTextProperty.h>
<vtkTubeFilter.h>
)
