SET( DEPENDENCIES_LIBRARIES
	iAbase
)
SET( DEPENDENCIES_IA_TOOLKIT_DIRS
	RemovePeaksOtsu    # for itkFHWRescaleIntensityImageFilter
)
# for ITK GPU filters using OpenCL:
SET( DEPENDENCIES_COMPILE_DEFINITIONS
	CL_HPP_TARGET_OPENCL_VERSION=${CL_HPP_TARGET_OPENCL_VERSION}
	CL_TARGET_OPENCL_VERSION=${CL_TARGET_OPENCL_VERSION}
)
