set(CommonImageFilters_PRECOMPILE_INCLUDES
<defines.h>
<iACastImageFilter.h>
<iAConnectedComponentFilters.h>
<iAConnector.h>
<iAConvolutionFilter.h>
<iADistanceMap.h>
<iAEdgeDetectionFilters.h>
<iAFilter.h>
<iAGeometricTransformations.h>
<iAGradients.h>
<iAHessianEigenanalysis.h>
<iAIntensity.h>
<iAItkVersion.h>
<iALog.h>
<iAMorphologyFilters.h>
<iANoiseFilters.h>
<iAProgress.h>
<iASmoothing.h>
<iAToolsITK.h>
<iATransformations.h>
<iATypedCallHelper.h>
<itkCastImageFilter.h>
<itkHessianRecursiveGaussianImageFilter.h>
<itkImageIOBase.h>
<itkImageRegionIterator.h>
<itkResampleImageFilter.h>
<itkRescaleIntensityImageFilter.h>
)
