SET (FoamCharacterization_PRECOMPILE_INCLUDES <iAConnector.h>
<iAFoamCharacterizationDialog.h>
<iAFoamCharacterizationItem.h>
<iAFoamCharacterizationItemBinarization.h>
<iAFoamCharacterizationItemDistanceTransform.h>
<iAFoamCharacterizationItemFilter.h>
<iAFoamCharacterizationItemWatershed.h>
<iAFoamCharacterizationTable.h>
<iAProgress.h>
<QApplication>
<QCheckBox>
<QComboBox>
<QDoubleSpinBox>
<QElapsedTimer>
<QFile>
<QGridLayout>
<QGroupBox>
<QLabel>
<QPushButton>
<vtkImageData.h>)
