set(CompVis_PRECOMPILE_INCLUDES
<iALog.h>
<iAMdiChild.h>
<iAVec3.h>
<map>
<QColor>
<QDialog>
<QDialogButtonBox>
<QDockWidget>
<QFileDialog>
<QGridLayout>
<QInputDialog>
<QLabel>
<QList>
<QMessageBox>
<QObject>
<QSettings>
<QStandardItem>
<QVBoxLayout>
<vector>
<vtkActor.h>
<vtkCamera.h>
<vtkLookupTable.h>
<vtkMath.h>
<vtkPointData.h>
<vtkPolyDataMapper.h>
<vtkPolyDataSilhouette.h>
<vtkProperty.h>
<vtkRenderer.h>
<vtkRendererCollection.h>
<vtkRenderWindow.h>
<vtkSmartPointer.h>
<vtkTable.h>
<vtkTextProperty.h>
)
