set(CompVis_PRECOMPILE_INCLUDES
<algorithm>
<cassert>
<chrono>
<cmath>
<cstdlib>
<dlg_CSVReader.h>
<fstream>
<iACoefficientOfVariation.h>
<iAComp3DWidget.h>
<iACompBayesianBlocksData.h>
<iACompBinning.h>
<iACompCombiTable.h>
<iACompCurve.h>
<iACompHistogramTable.h>
<iACompHistogramTableData.h>
<iACompHistogramVis.h>
<iACompKernelDensityEstimationData.h>
<iACompNaturalBreaksData.h>
<iACompTable.h>
<iACompTableInteractorStyle.h>
<iACompUniformBinningData.h>
<iACompUniformTable.h>
<iACompVariableTable.h>
<iACompVisMain.h>
<iACompVisOptions.h>
<iACorrelationCoefficient.h>
<iACsvConfig.h>
<iACsvDataStorage.h>
<iALog.h>
<iAMainWindow.h>
<iAMultidimensionalScaling.h>
<iAQVTKWidget.h>
<iASimilarityDistance.h>
<iostream>
<limits>
<map>
<QBoxLayout>
<QDockWidget>
<QList>
<QString>
<vector>
<vtkActor.h>
<vtkAlgorithmOutput.h>
<vtkCamera.h>
<vtkCellData.h>
<vtkCellPicker.h>
<vtkColorTransferFunction.h>
<vtkDoubleArray.h>
<vtkFloatArray.h>
<vtkLineSource.h>
<vtkLookupTable.h>
<vtkMapper.h>
<vtkNew.h>
<vtkObjectFactory.h>
<vtkPlaneSource.h>
<vtkPointData.h>
<vtkPoints.h>
<vtkPolyData.h>
<vtkPolyDataMapper.h>
<vtkPolyLine.h>
<vtkProgrammableGlyphFilter.h>
<vtkProperty.h>
<vtkPropPicker.h>
<vtkRenderer.h>
<vtkRendererCollection.h>
<vtkRenderWindow.h>
<vtkRenderWindowInteractor.h>
<vtkScalarBarActor.h>
<vtkSmartPointer.h>
<vtkSphereSource.h>
<vtkStringArray.h>
<vtkTable.h>
<vtkTextActor.h>
<vtkTextProperty.h>
<vtkUnsignedCharArray.h>)
