set(InSpectr_PRECOMPILE_INCLUDES
<algorithm>
<cassert>
<dlg_InSpectr.h>
<iAAccumulatedXRFData.h>
<iACharacteristicEnergy.h>
<iAElementalDecomposition.h>
<iAElementConcentrations.h>
<iAElementConstants.h>
<iAElementSelectionListener.h>
<iAEnergySpectrum.h>
<iAFunctionalBoxplot.h>
<iAMathUtility.h>
<iAMdiChild.h>
<iAPeriodicTableWidget.h>
<iASpectrumFilter.h>
<iATypedCallHelper.h>
<iAXRFData.h>
<QFileDialog>
<QImage>
<QMap>
<QMouseEvent>
<QPainter>
<QSharedPointer>
<qthelper/iAQTtoUIConnector.h>
<QThread>
<QVector>
<QWidget>
<vector>
<vtkColorTransferFunction.h>
<vtkImageData.h>
<vtkMath.h>
<vtkPiecewiseFunction.h>
<vtkSmartPointer.h>)
