set(FeatureAnalyzer_PRECOMPILE_INCLUDES
<defines.h>
<FeatureAnalyzerHelpers.h>
<iABoxPlotData.h>
<iABPMData.h>
<iAChanData.h>
<iAChannelData.h>
<iACSVToQTableWidgetConverter.h>
<iADataFolderDialog.h>
<iAFAQSplom.h>
<iAFeatureAnalyzer.h>
<iAFeatureAnalyzerModuleInterface.h>
<iAFeatureAnalyzerProject.h>
<iAFileUtils.h>
<iAHistogramData.h>
<iAHistogramPlotData.h>
<iAHMData.h>
<iAITKIO.h>
<iALog.h>
<iALUT.h>
<iAMainWindow.h>
<iAModuleDispatcher.h>
<iAPDMView.h>
<iAPreviewSPLOM.h>
<iAPreviewSPLOMView.h>
<iAQtVTKBindings.h>
<iAQVTKWidget.h>
<iARangeSliderDiagramView.h>
<iARangeSliderDiagramWidget.h>
<iARendererViewSync.h>
<iASegm3DView.h>
<iASelection.h>
<iASelectionsView.h>
<iASPLOMData.h>
<iASPMView.h>
<iASSSlicer.h>
<iASSView.h>
<iATransferFunction.h>
<iATreeView.h>
<QCheckBox>
<QColor>
<QDir>
<QDockWidget>
<QHBoxLayout>
<QLabel>
<QList>
<QMap>
<QMenu>
<QMessageBox>
<QModelIndex>
<QMouseEvent>
<QPainter>
<QPixmap>
<QScopedPointer>
<QSettings>
<QSharedPointer>
<QString>
<QTableWidget>
<QTreeWidget>
<QVBoxLayout>
<vtkColorTransferFunction.h>
<vtkContextScene.h>
<vtkContextView.h>
<vtkDistancePolyDataFilter.h>
<vtkDoubleArray.h>
<vtkIdTypeArray.h>
<vtkImageData.h>
<vtkLookupTable.h>
<vtkMarchingContourFilter.h>
<vtkNew.h>
<vtkPiecewiseFunction.h>
<vtkPlot.h>
<vtkPointData.h>
<vtkPolyData.h>
<vtkRenderer.h>
<vtkRenderWindow.h>
<vtkScalarBarActor.h>
<vtkScalarBarRepresentation.h>
<vtkScalarBarWidget.h>
<vtkSelection.h>
<vtkSmartPointer.h>
<vtkTable.h>
<vtkTextProperty.h>
<vtkTransform.h>
<vtkVector.h>
)
