set(FeatureAnalyzer_PRECOMPILE_INCLUDES
<defines.h>
<FeatureAnalyzerHelpers.h>
<iAChanData.h>
<iAChannelData.h>
<iACSVToQTableWidgetConverter.h>
<iAFeatureAnalyzerTool.h>
<iALog.h>
<iALUT.h>
<iAMainWindow.h>
<iASegm3DView.h>
<iASelection.h>
<QDir>
<QDockWidget>
<QLabel>
<QList>
<QMap>
<QMenu>
<QModelIndex>
<QMultiMap>
<QScopedPointer>
<QSettings>
<QStringList>
<QTableWidget>
<qthelper/iAQTtoUIConnector.h>
<QTreeWidget>
<QVBoxLayout>
<vtkColorTransferFunction.h>
<vtkIdTypeArray.h>
<vtkImageData.h>
<vtkLookupTable.h>
<vtkPiecewiseFunction.h>
<vtkRenderer.h>
<vtkScalarBarActor.h>
<vtkScalarBarWidget.h>
<vtkSmartPointer.h>
<vtkTransform.h>)
