set(OPENIA_PRECOMPILE_HEADERS
<cstdio>
<cstring>
<memory>
<vector>
<iAAmiraMeshIO.h>
<iAAutoRegistration.h>
<iAConnector.h>
<iADataSet.h>
<iADataSetType.h>
<iAExceptionThrowingErrorObserver.h>
<iAFileIO.h>
<iAFileStackParams.h>
<iAFileTypeRegistry.h>
<iAFileUtils.h>
<iAITKIO.h>
<iALog.h>
<iAOIFReader.h>
<iAProgress.h>
<iARawFileIO.h>
<iASettings.h>
<iAStringHelper.h>
<iAToolsITK.h>
<iAToolsVTK.h>
<iAValueTypeVectorHelpers.h>
<itkImage.h>
<itkImageSeriesWriter.h>
<itkNumericSeriesFileNames.h>
<QFile>
<QFileInfo>
<QMap>
<QSettings>
<QString>
<QTextStream>
<vtkImageData.h>
<vtkPointData.h>
<vtkPolyData.h>
<vtkSmartPointer.h>
)
