set(OPENIA_PRECOMPILE_HEADERS
<cstdio>
<cstring>
<vector>
<defines.h>
<iAAmiraMeshIO.h>
<iAAmiraVolumeFileIO.h>
<iAConnector.h>
<iACSVImageFileIO.h>
<iADataSet.h>
<iADataSetType.h>
<iADCMFileIO.h>
<iAExceptionThrowingErrorObserver.h>
<iAFileIO.h>
<iAFileTypeRegistry.h>
<iAFileUtils.h>
<iAGraphFileIO.h>
<iAHDF5IO.h>
<iAImageStackFileIO.h>
<iALog.h>
<iAMetaFileIO.h>
<iANKCFileIO.h>
<iAOIFFileIO.h>
<iAOIFReader.h>
<iAProgress.h>
<iAProjectFileIO.h>
<iARawFileIO.h>
<iASTLFileIO.h>
<iAToolsVTK.h>
<iAValueTypeVectorHelpers.h>
<iAVGIFileIO.h>
<iAVTIFileIO.h>
<iAVTKFileIO.h>
<itkImage.h>
<QFile>
<QFileInfo>
<QMap>
<QString>
<QTextStream>
<vtkImageData.h>
<vtkPointData.h>
<vtkPolyData.h>
<vtkSmartPointer.h>
)
