set(NModalTF_PRECOMPILE_INCLUDES
<iAChannelData.h>
<iAImageData.h>
<iALog.h>
<iAMdiChild.h>
<iANModalBackgroundRemover.h>
<iANModalDisplay.h>
<iANModalObjects.h>
<iANModalProgressWidget.h>
<iAPerformanceHelper.h>
<iASlicer.h>
<iASlicerMode.h>
<iATypedCallHelper.h>
<memory>
<QDialog>
<QGridLayout>
<QLabel>
<QList>
<QMap>
<QPushButton>
<QSlider>
<QVBoxLayout>
<QWidget>
<vtkColorTransferFunction.h>
<vtkImageData.h>
<vtkPiecewiseFunction.h>
<vtkSmartPointer.h>)
