if (NOT EXISTS "${TARGET_DIR}" OR "${SOURCE_DIR}" IS_NEWER_THAN "${TARGET_DIR}")
	message("Copying  ${SOURCE_DIR} to ${TARGET_DIR}.")
	execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_directory "${SOURCE_DIR}" "${TARGET_DIR}"
		RESULT_VARIABLE res OUTPUT_VARIABLE out)
	if (NOT "${res}" EQUAL "0")
		message(SEND_ERROR "  Copying ${SOURCE_DIR} to ${TARGET_DIR} FAILED! exit code=${res}, output: ${out}")
	endif()
else()
	message("Target folder ${TARGET_DIR} exists and is current, not copying it from ${SOURCE_DIR}!")
endif()
