set(GEMSe_PRECOMPILE_INCLUDES
<cassert>
<dlg_GEMSe.h>
<dlg_samplings.h>
<iAAttitudes.h>
<iAAttributeDescriptor.h>
<iAAttributes.h>
<iAChartAttributeMapper.h>
<iAChartFilter.h>
<iAClusterAttribChart.h>
<iAColorTheme.h>
<iAConnector.h>
<iAFakeTreeNode.h>
<iAGEMSeConstants.h>
<iAGEMSeTool.h>
<iAImageData.h>
<iAImageNodeWidget.h>
<iAImagePreviewWidget.h>
<iAImageTree.h>
<iAImageTreeInternalNode.h>
<iAImageTreeLeaf.h>
<iAImageTreeNode.h>
<iAITKIO.h>
<iALabelInfo.h>
<iALog.h>
<iAMathUtility.h>
<iAMdiChild.h>
<iAMeasures.h>
<iAParamHistogramData.h>
<iAPlotTypes.h>
<iAPreviewWidgetPool.h>
<iAProgress.h>
<iAQtCaptionWidget.h>
<iAQTtoUIConnector.h>
<iARepresentative.h>
<iASamplingResults.h>
<iASEAFile.h>
<iASingleResult.h>
<iASlicerMode.h>
<iAToolsITK.h>
<itkLabelOverlapMeasuresImageFilter.h>
<memory>
<QCheckBox>
<QFile>
<QFileDialog>
<QFileInfo>
<QGridLayout>
<QHBoxLayout>
<QLabel>
<QMap>
<QMessageBox>
<QMouseEvent>
<QPainter>
<QSplitter>
<QTextStream>
<QVBoxLayout>
<QVector>
<QWidget>
<vtkImageData.h>
<vtkSmartPointer.h>)
