SET (GEMSe_PRECOMPILE_INCLUDES <cassert>
<charts/iAPlotTypes.h>
<dlg_commoninput.h>
<dlg_GEMSe.h>
<dlg_labels.h>
<dlg_modalities.h>
<dlg_progress.h>
<dlg_samplings.h>
<iAAttitudes.h>
<iAAttributeDescriptor.h>
<iAAttributes.h>
<iAChannelData.h>
<iAChartAttributeMapper.h>
<iAChartFilter.h>
<iAClusterAttribChart.h>
<iAColorTheme.h>
<iAConnector.h>
<iAFakeTreeNode.h>
<iAGEMSeConstants.h>
<iAGEMSeProject.h>
<iAImageCoordinate.h>
<iAImageNodeWidget.h>
<iAImagePreviewWidget.h>
<iAImageTree.h>
<iAImageTreeInternalNode.h>
<iAImageTreeLeaf.h>
<iAImageTreeNode.h>
<iALabelInfo.h>
<iALabelOverlayThread.h>
<iALog.h>
<iAMathUtility.h>
<iAMeasures.h>
<iAModality.h>
<iAModalityList.h>
<iAParamHistogramData.h>
<iAPreviewWidgetPool.h>
<iAQtCaptionWidget.h>
<iARepresentative.h>
<iASamplingResults.h>
<iASEAFile.h>
<iASingleResult.h>
<iASlicer.h>
<iASlicerMode.h>
<iAToolsITK.h>
<iAToolsVTK.h>
<iAVtkDraw.h>
<io/iAFileUtils.h>
<io/iAITKIO.h>
<itkLabelOverlapMeasuresImageFilter.h>
<mainwindow.h>
<mdichild.h>
<QCheckBox>
<QFile>
<QFileDialog>
<QFileInfo>
<QGridLayout>
<QHBoxLayout>
<QLabel>
<QMap>
<QMessageBox>
<QMouseEvent>
<QPainter>
<QSharedPointer>
<QSplitter>
<QStandardItemModel>
<QTextStream>
<qthelper/iAQTtoUIConnector.h>
<QThread>
<QVBoxLayout>
<QVector>
<QWidget>
<vtkImageData.h>
<vtkLookupTable.h>
<vtkPiecewiseFunction.h>
<vtkSmartPointer.h>)
