set(GEMSe_PRECOMPILE_INCLUDES
<iAPlotTypes.h>
<dlg_GEMSe.h>
<dlg_samplings.h>
<iAAttitudes.h>
<iAAttributeDescriptor.h>
<iAAttributes.h>
<iAChannelData.h>
<iAChartAttributeMapper.h>
<iAChartFilter.h>
<iAClusterAttribChart.h>
<iAColorTheme.h>
<iAConnector.h>
<iAFakeTreeNode.h>
<iAGEMSeConstants.h>
<iAGEMSeProject.h>
<iAImageCoordinate.h>
<iAImageNodeWidget.h>
<iAImagePreviewWidget.h>
<iAImageTree.h>
<iAImageTreeInternalNode.h>
<iAImageTreeLeaf.h>
<iAImageTreeNode.h>
<iALabelInfo.h>
<iALog.h>
<iAMathUtility.h>
<iAMeasures.h>
<iAParamHistogramData.h>
<iAPreviewWidgetPool.h>
<iAQtCaptionWidget.h>
<iARepresentative.h>
<iASamplingResults.h>
<iASEAFile.h>
<iASingleResult.h>
<iASlicer.h>
<iASlicerMode.h>
<iAToolsITK.h>
<iAToolsVTK.h>
<iAVtkDraw.h>
<iAFileUtils.h>
<iAITKIO.h>
<itkLabelOverlapMeasuresImageFilter.h>
<iAMainWindow.h>
<iAMdiChild.h>
<qthelper/iAQTtoUIConnector.h>

<QCheckBox>
<QFile>
<QFileDialog>
<QFileInfo>
<QGridLayout>
<QHBoxLayout>
<QLabel>
<QMap>
<QMessageBox>
<QMouseEvent>
<QPainter>
<QSharedPointer>
<QSplitter>
<QStandardItemModel>
<QTextStream>
<QThread>
<QVBoxLayout>
<QVector>
<QWidget>

<vtkImageData.h>
<vtkLookupTable.h>
<vtkPiecewiseFunction.h>
<vtkSmartPointer.h>

<cassert>
)
