set(OPENIA_PRECOMPILE_HEADERS
<cassert>
<vector>
<iALog.h>
<iARenderObserver.h>
<QColor>
<QObject>
<vtkCamera.h>
<vtkCellLocator.h>
<vtkCommand.h>
<vtkImageData.h>
<vtkPlane.h>
<vtkPolyDataMapper.h>
<vtkRenderer.h>
<vtkRenderWindowInteractor.h>
<vtkSmartPointer.h>
<vtkTransform.h>
)
