IF (openiA_TESTING_ENABLED)
	get_filename_component(CoreSrcDir "../libs/base" REALPATH BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
	get_filename_component(CoreBinDir "../libs" REALPATH BASE_DIR "${CMAKE_CURRENT_BINARY_DIR}")
	ADD_EXECUTABLE(MDSTest FiAKEr/iAMultiDimensionalScalingTest.cpp FiAKEr/iAMultidimensionalScaling.cpp)
	TARGET_LINK_LIBRARIES(MDSTest PRIVATE ${QT_LIBRARIES})
	TARGET_INCLUDE_DIRECTORIES(MDSTest PRIVATE
		${CoreSrcDir}                         # for iAStringHelper, required by MDS
		${CoreBinDir}                         # for iAbase_export.h
		${CMAKE_CURRENT_BINARY_DIR}           # for _export.h
	)
	TARGET_COMPILE_DEFINITIONS(MDSTest PRIVATE NO_DLL_LINKAGE)
	ADD_TEST(NAME MDSTest COMMAND MDSTest)
	IF (MSVC)
		STRING(REGEX REPLACE "/" "\\\\" QT_WIN_DLL_DIR ${QT_LIB_DIR})
		MESSAGE(STATUS "TEST QT DIR: ${QT_LIB_DIR}")
		SET_TESTS_PROPERTIES(MDSTest PROPERTIES ENVIRONMENT "PATH=${QT_WIN_DLL_DIR};$ENV{PATH}")
		SET_TARGET_PROPERTIES(MDSTest PROPERTIES VS_DEBUGGER_ENVIRONMENT "PATH=${QT_WIN_DLL_DIR};$ENV{PATH}")
	ELSE()
		target_compile_options(MDSTest PRIVATE -fPIC)
	ENDIF()
	IF (openiA_USE_IDE_FOLDERS)
		SET_PROPERTY(TARGET MDSTest PROPERTY FOLDER "Tests")
	ENDIF()
ENDIF()
