set(FiAKEr_PRECOMPILE_INCLUDES
<iASPLOMData.h>
<iACsvConfig.h>
<iAFiAKErController.h>
<iAFiberResult.h>
<iAFiberData.h>
<iALog.h>
<iAMathUtility.h>
<iARefDistCompute.h>
<iAVec3.h>
<QMap>
<QMessageBox>
<QSettings>
<QSharedPointer>
<qthelper/iAQTtoUIConnector.h>
<vector>
<vtkSmartPointer.h>
<vtkTable.h>)
