set(FiAKEr_PRECOMPILE_INCLUDES
<array>
<iAColorTheme.h>
<iACsvConfig.h>
<iAFiAKErController.h>
<iAFiberData.h>
<iAFiberResult.h>
<iAFileUtils.h>
<iALog.h>
<iALUT.h>
<iAMainWindow.h>
<iAMathUtility.h>
<iAMdiChild.h>
<iAMeasureSelectionDlg.h>
<iAModuleDispatcher.h>
<iAMultidimensionalScaling.h>
<iAProgress.h>
<iAQVTKWidget.h>
<iARefDistCompute.h>
<iASensitivityData.h>
<iASignallingWidget.h>
<iASPLOMData.h>
<iAStackedBarChart.h>
<iAStringHelper.h>
<iAToolsVTK.h>
<iAVec3.h>
<QAction>
<QApplication>
<QFileDialog>
<QFileInfo>
<QGridLayout>
<QLabel>
<QMap>
<QMenu>
<QMessageBox>
<QMouseEvent>
<QPainter>
<QScrollArea>
<QSettings>
<QSharedPointer>
<QStandardItemModel>
<QTextStream>
<qthelper/iAQTtoUIConnector.h>
<QWidget>
<vector>
<vtkPointData.h>
<vtkPolyData.h>
<vtkProperty.h>
<vtkRendererCollection.h>
<vtkRenderWindow.h>
<vtkSmartPointer.h>
<vtkTable.h>
<vtkUnsignedCharArray.h>
<vtkVariant.h>
<vtkVertexGlyphFilter.h>)
