SET (4DCT_PRECOMPILE_INCLUDES <dlg_4DCTFileOpen.h>
<fstream>
<iA4DCTData.h>
<iA4DCTDefects.h>
<iA4DCTFileData.h>
<iA4DCTMainWin.h>
<iA4DCTSettings.h>
<iA4DCTStageData.h>
<iA4DCTVisWin.h>
<iABoundingBoxVisModule.h>
<iADefectVisModule.h>
<iAFeature.h>
<iAFractureVisModule.h>
<iAMhdFileInfo.h>
<iAPlaneVisModule.h>
<iARegionVisModule.h>
<iAStageView.h>
<iAvec3.h>
<iAVisModule.h>
<iAVisModuleItem.h>
<iAVisModulesCollection.h>
<io/iAFileUtils.h>
<itkImage.h>
<itkImageFileReader.h>
<itkImageFileWriter.h>
<itkImageToVTKImageFilter.h>
<itkResampleImageFilter.h>
<mainwindow.h>
<map>
<QColor>
<QDialog>
<QDir>
<QDockWidget>
<QFileDialog>
<QFileInfo>
<QLabel>
<QList>
<QPixmap>
<QSettings>
<QString>
<QStringList>
<QVector>
<QWidget>
<vector>
<vtkActor.h>
<vtkImageData.h>
<vtkMetaImageReader.h>
<vtkPolyDataMapper.h>
<vtkProperty.h>
<vtkRenderer.h>
<vtkSmartPointer.h>)
