name: "Build doxygen API doc"

on:
  release:
    types: [published]
  workflow_dispatch

jobs:
  builddoc:
    name: Generate API doc
  steps:
  - name: Run doxygen
    uses: mattnotmitt/doxygen-action@v1.9.5
    with:
      working-directory: '.'
      doxyfile-path: 'Doxyfile'
