name: "Build doxygen API doc"

on:
  # manual triggering allowed:
  workflow_dispatch:
  # or on a new release:
  release:                
    types: [published]

jobs:
  builddoc:
    name: Generate API doc
  steps:
  - name: Run doxygen
    uses: mattnotmitt/doxygen-action@v1.9.5
    with:
      working-directory: '.'
      doxyfile-path: 'Doxyfile'
