SET (OPENIA_PRECOMPILE_HEADERS
<cassert>
<cstdio>
<string>
<vector>

<defines.h>
<dlg_commoninput.h>
<iAAbortListener.h>
<iAAlgorithm.h>
<iAAttributeDescriptor.h>
<iAChannelData.h>
<iAChannelSlicerData.h>
<iAConnector.h>
<iAFileUtils.h>
<iAFilter.h>
<iAFilterRunnerGUI.h>
<iAFilterRunnerRegistry.h>
<iAFilterSelectionDlg.h>
<iAJobListView.h>
<iALog.h>
<iALogger.h>
<iAMainWindow.h>
<iAMdiChild.h>
<iAModality.h>
<iAModalityList.h>
<iAModalityTransfer.h>
<iAProgress.h>
<iASlicerMode.h>
<iAStringHelper.h>
<iAToolsVTK.h>
<iAVolumeRenderer.h>
<iAVolumeSettings.h>
<iAVtkVersion.h>

<itkImage.h>

<QCheckBox>
<QComboBox>
<QFileDialog>
<QFileInfo>
<QLabel>
<QLineEdit>
<QMap>
<QMessageBox>
<QObject>
<QPushButton>
<QSettings>
<QSharedPointer>
<QSpinBox>
<QString>
<QThread>
<QVariant>
<QVector>
<QWidget>

<QVTKInteractor.h>
<vtkActor.h>
<vtkActor2D.h>
<vtkCamera.h>
<vtkCellArray.h>
<vtkColorTransferFunction.h>
<vtkCommand.h>
<vtkGenericOpenGLRenderWindow.h>
<vtkImageActor.h>
<vtkImageData.h>
<vtkImageMapper3D.h>
<vtkImageMapToColors.h>
<vtkImageReslice.h>
<vtkMath.h>
<vtkPiecewiseFunction.h>
<vtkPoints.h>
<vtkPolyData.h>
<vtkPolyDataMapper.h>
<vtkPolyDataMapper2D.h>
<vtkPolyLine.h>
<vtkProperty.h>
<vtkProperty2D.h>
<vtkRenderer.h>
<vtkRendererCollection.h>
<vtkSmartPointer.h>
<vtkTransform.h>
<vtkVolume.h>
)