SET (OPENIA_PRECOMPILE_HEADERS
<defines.h>
<dlg_commoninput.h>
<iAAbortListener.h>
<iAChannelData.h>
<iAChannelSlicerData.h>
<iAConnector.h>
<iAFileUtils.h>
<iAFilter.h>
<iAFilterRunnerGUI.h>
<iAFilterRunnerRegistry.h>
<iAFilterSelectionDlg.h>
<iAJobListView.h>
<iALineSegment.h>
<iALog.h>
<iALogger.h>
<iAMainWindow.h>
<iAMdiChild.h>
<iAModality.h>
<iAModalityList.h>
<iAModalityTransfer.h>
<iAProgress.h>
<iASlicer.h>
<iASlicerMode.h>
<iAStringHelper.h>
<iAToolsVTK.h>
<iATypedCallHelper.h>
<iAVolumeRenderer.h>
<iAVolumeSettings.h>
<iAVtkVersion.h>
<iAVtkWidget.h>

<vtkActor.h>
<vtkActor2D.h>
<vtkCamera.h>
<vtkCellArray.h>
<vtkColorTransferFunction.h>
<vtkCommand.h>
<vtkDiskSource.h>
<vtkGenericOpenGLRenderWindow.h>
<vtkImageActor.h>
<vtkImageData.h>
<vtkImageMapper3D.h>
<vtkImageReslice.h>
<vtkLineSource.h>
<vtkMath.h>
<vtkObjectFactory.h>
<vtkPiecewiseFunction.h>
<vtkPointData.h>
<vtkPoints.h>
<vtkPolyData.h>
<vtkPolyDataMapper.h>
<vtkPolyDataMapper2D.h>
<vtkPolyLine.h>
<vtkProperty.h>
<vtkRenderer.h>
<vtkRendererCollection.h>
<vtkRenderWindowInteractor.h>
<vtkSmartPointer.h>
<vtkTextProperty.h>
<vtkTransform.h>
<vtkVolume.h>

<QColor>
<QComboBox>
<QFileDialog>
<QFileInfo>
<QLabel>
<QLineEdit>
<QMap>
<QMessageBox>
<QMouseEvent>
<QObject>
<QPainter>
<QPushButton>
<QSettings>
<QSharedPointer>
<QString>
<QVector>
<QVTKInteractor.h>
<QWidget>

<cassert>
<vector>
)