SET (OPENIA_PRECOMPILE_HEADERS
<cassert>
<chrono>
<cmath>
<cstdint>
<cstdio>
<cstdlib>
<cstring>
<defines.h>
<dlg_commoninput.h>
<dlg_modalities.h>
<dlg_modalityProperties.h>
<dlg_openfile_sizecheck.h>
<iAAbortListener.h>
<iAAbstractMagicLensWidget.h>
<iAAlgorithm.h>
<iAAttributeDescriptor.h>
<iAChannelData.h>
<iAChannelSlicerData.h>
<iAConnector.h>
<iAFast3DMagicLensWidget.h>
<iAFileUtils.h>
<iAFilter.h>
<iAFilterRegistry.h>
<iAFilterRunnerGUI.h>
<iAFilterRunnerRegistry.h>
<iAFilterSelectionDlg.h>
<iAGUIModuleInterface.h>
<iAJobListView.h>
<iALog.h>
<iALogger.h>
<iAMainWindow.h>
<iAMathUtility.h>
<iAMdiChild.h>
<iAModality.h>
<iAModalityList.h>
<iAModalityTransfer.h>
<iAModuleAttachmentToChild.h>
<iAModuleInterface.h>
<iAParameterDlg.h>
<iAPerformanceHelper.h>
<iAProgress.h>
<iASlicerMode.h>
<iAStringHelper.h>
<iAToolsVTK.h>
<iATransferFunction.h>
<iATypedCallHelper.h>
<iAVolumeRenderer.h>
<iAVolumeSettings.h>
<iAVolumeStack.h>
<iAvtkInteractStyleActor.h>
<iAVtkVersion.h>
<iAVtkWidget.h>
<iAXmlSettings.h>
<iostream>
<itkImage.h>
<itkImageFileReader.h>
<itkMacro.h>
<QCheckBox>
<QColor>
<QComboBox>
<QDialog>
<QDir>
<QErrorMessage>
<QFileDialog>
<QFileInfo>
<QImage>
<QLabel>
<QLineEdit>
<QMainWindow>
<QMap>
<QMenu>
<QMessageBox>
<QObject>
<QPlainTextEdit>
<QPushButton>
<QScrollArea>
<QSettings>
<QSharedPointer>
<QSpinBox>
<QStack>
<QStatusBar>
<QString>
<QStringList>
<QTextBrowser>
<QTextDocument>
<QTextStream>
<QThread>
<QToolButton>
<QVariant>
<QVector>
<QVTKInteractor.h>
<QWidget>
<string>
<ui_CommonInput.h>
<vector>
<vtkActor.h>
<vtkActor2D.h>
<vtkCamera.h>
<vtkCellArray.h>
<vtkColorTransferFunction.h>
<vtkCommand.h>
<vtkGenericOpenGLRenderWindow.h>
<vtkImageActor.h>
<vtkImageData.h>
<vtkImageMapper3D.h>
<vtkImageMapToColors.h>
<vtkImageReslice.h>
<vtkLineSource.h>
<vtkLookupTable.h>
<vtkMarchingContourFilter.h>
<vtkMath.h>
<vtkObjectFactory.h>
<vtkPiecewiseFunction.h>
<vtkPointData.h>
<vtkPoints.h>
<vtkPolyData.h>
<vtkPolyDataMapper.h>
<vtkPolyDataMapper2D.h>
<vtkPolyLine.h>
<vtkProperty.h>
<vtkProperty2D.h>
<vtkRenderer.h>
<vtkRendererCollection.h>
<vtkScalarsToColors.h>
<vtkSmartPointer.h>
<vtkTextProperty.h>
<vtkTransform.h>
<vtkVolume.h>
<vtkVolumeProperty.h>
)
